export const Images = [
  { name: 'minecart.png'                   },
  { name: 'bartop.jpg'                     },
  { name: 'clyde-steph.jpg'                },
  { name: 'clyde-cat.jpg',   maxWidth: 300 },
  { name: 'tackle.jpeg',     maxWidth: 410 },
  { name: 'paper-plane.jpg', maxWidth: 200 },
  { name: 'harpie.jpg'                     },
  { name: 'reykjavik.jpg',   maxWidth: 300 },
  { name: 'special.jpeg',    maxWidth: 300 },
  { name: 'butt-hammer.jpg', maxWidth: 200 },
];

export const Sounds = [
  // IA Soundboard
  { category: 'ia', label: 'Angels',            icon: 'rick.jpg',           sound:'angels.mp3'         },
  { category: 'ia', label: 'Oh No',             icon: 'knuckles.jpg',       sound:'ohno.mp3'           },
  { category: 'ia', label: 'Robot Friend',      icon: 'butters.jpg',        sound:'robot.mp3'          },
  { category: 'ia', label: 'Baked Beans',       icon: 'bakedbeans.jpg',     sound:'bakedbeans.mp3'     },
  { category: 'ia', label: 'How Could This',    icon: 'howcouldthis.jpg',   sound:'howcouldthis.mp3'   },
  { category: 'ia', label: 'Probe Droid',       icon: 'probedroid.png',     sound:'probedroid.mp3'     },
  { category: 'ia', label: 'Gandalf Europop',   icon: 'gandalfeuropop.png', sound:'gandalfeuropop.mp3' },
  { category: 'ia', label: 'What a Time',       icon: 'moonpie.jpg',        sound:'whatatime.mp3'      },
  { category: 'ia', label: 'Holy Hand Grenade', icon: 'handgrenade.png',    sound:'handgrenade.mp3'    },

  // Dnd Soundboard
  { category: 'dnd', label: 'Quest Accepted',     icon: 'skyrim_quest.png',   sound: 'skyrim_quest.mp3'   },
  { category: 'dnd', label: 'Stop Right There!',  icon: 'scum.png',           sound: 'scum.mp3'           },
  { category: 'dnd', label: 'It\'s a Trap!',      icon: 'ackbar.jpg',         sound: 'ackbar.mp3'         },
  { category: 'dnd', label: 'Alert',              icon: 'alert.jpg',          sound: 'alert.mp3'          },
  { category: 'dnd', label: 'Wii Shop',           icon: 'wii_shop.jpg',       sound: 'wii_shop.mp3'       },
  { category: 'dnd', label: 'Zelda Shop',         icon: 'zelda_shop.jpg',     sound: 'zelda_shop.mp3'     },
  { category: 'dnd', label: 'FF7 Victory',        icon: 'ff7.jpg',            sound: 'ff7.mp3'            },
  { category: 'dnd', label: 'Search for Traps',   icon: 'pookie.jpg',         sound: 'pookie.mp3'         },
  { category: 'dnd', label: 'Pokemon Battle',     icon: 'pokemon.jpg',        sound: 'pokemon.mp3'        },
  { category: 'dnd', label: 'Ghost Town',         icon: 'sean.png',           sound: 'sean.mp3'           },
  { category: 'dnd', label: 'Dun Dun Duuuunn!!',  icon: 'dundundun.jpg',      sound: 'dundundun.mp3'      },
  { category: 'dnd', label: 'Bombom ba bom',      icon: 'trombone.jpg',       sound: 'fail_trombone.mp3'  },
  { category: 'dnd', label: 'A Lot of Damage',    icon: 'phil_swift.jpg',     sound: 'lotta_damage_1.mp3' },
  { category: 'dnd', label: 'A Lot of Damage?',   icon: 'jontron.png',        sound: 'lotta_damage_2.mp3' },
  { category: 'dnd', label: 'Bat Transition',     icon: 'bat_transition.jpg', sound: 'bat_transition.mp3' },
  { category: 'dnd', label: 'Yaaaaaayyyy',        icon: 'happy_children.jpg', sound: 'yaaay.mp3'          },
  { category: 'dnd', label: 'Bwa bwa bwaaa',      icon: 'sad_trombone.jpg',   sound: 'sad_trombone.mp3'   },
  { category: 'dnd', label: 'God Have Mercy',     icon: 'mercy.jpg',          sound: 'mercy.mp3'          },
  { category: 'dnd', label: 'Toast - Yes!',       icon: 'yes.jpg',            soundPrefix: 'yes_', max: 11 },
  { category: 'dnd', label: "The Garbage Man",    icon: 'garbage_man.png',   sound: 'garbage_man.mp3'       },
  { category: 'dnd', label: "The Tower!",         icon: 'the_tower.jpg',     sound: 'tower.mp3'             },
  { category: 'dnd', label: "Chest Opening",      icon: 'chest_opening.png', sound: 'chest_opening.mp3'     },
  { category: 'dnd', label: "Chest Prize",        icon: 'chest_prize.jpg',   sound: 'chest_prize.mp3'       },
  { category: 'dnd', label: "Gridders' Lament",   icon: 'dulcimer.jpg',      sound: 'dulcimer.mp3'          },
  { category: 'dnd', label: "Enemy Approaching",  icon: 'enemy.jpg',         sound: 'enemy_approaching.mp3' },
  { category: 'dnd', label: "No God No",          icon: 'nogodno.jpg',       sound: 'nogodno.mp3'           },
  { category: 'dnd', label: "Wilhelm Scream",     icon: 'wilhelm.jpg',       sound: 'wilhelm.mp3'           },
  { category: 'dnd', label: 'That\'s Hot',        icon: 'thatshot.jpg',      soundPrefix: 'thatshot', max: 3 },
  { category: 'dnd', label: "FF7 Fight",          icon: 'ff7fight.jpg',      sound: 'ff7fight.mp3'          },
  { category: 'dnd', label: "OOF",                icon: 'oof.jpg',           sound: 'oof.mp3'               },
  { category: 'dnd', label: "You Died!",          icon: 'mcoof.png',         sound: 'mcoof.mp3'             },
  { category: 'dnd', label: "Howie Scream",       icon: 'howie.jpg',         sound: 'howie.mp3'             },
  { category: 'dnd', label: "Curb",               icon: 'curb.jpg',          sound: 'curb.mp3'              },
  { category: 'dnd', label: 'Oblivion Guard',     icon: 'scum.png',          soundPrefix: 'guard', max: 21  },
  { category: 'dnd', label: 'Democracy Manifest', icon: 'dm.jpg',            soundPrefix: 'dm',    max: 10  },
];
