export const Images = [
  { name: 'minecart.png'                   },
  { name: 'bartop.jpg'                     },
  { name: 'clyde-steph.jpg'                },
  { name: 'clyde-cat.jpg',   maxWidth: 300 },
  { name: 'tackle.jpeg',     maxWidth: 410 },
  { name: 'paper-plane.jpg', maxWidth: 200 },
  { name: 'harpie.jpg'                     },
  { name: 'reykjavik.jpg',   maxWidth: 300 },
  { name: 'special.jpeg',    maxWidth: 300 },
  { name: 'butt-hammer.jpg', maxWidth: 200 },
];

export const Sounds = [
  // IA Soundboard
  { label: 'Angels',            icon: 'rick.jpg',           sound:'angels'         },
  { label: 'Oh No',             icon: 'knuckles.jpg',       sound:'ohno'           },
  { label: 'Robot Friend',      icon: 'butters.jpg',        sound:'robot'          },
  { label: 'Baked Beans',       icon: 'bakedbeans.jpg',     sound:'bakedbeans'     },
  { label: 'How Could This',    icon: 'howcouldthis.jpg',   sound:'howcouldthis'   },
  { label: 'Probe Droid',       icon: 'probedroid.png',     sound:'probedroid'     },
  { label: 'Gandalf Europop',   icon: 'gandalfeuropop.png', sound:'gandalfeuropop' },
  { label: 'What a Time',       icon: 'moonpie.jpg',        sound:'whatatime'      },
  { label: 'Holy Hand Grenade', icon: 'handgrenade.png',    sound:'handgrenade'    },

  // Dnd Soundboard
  { label: 'Quest Accepted',    icon: 'skyrim_quest.png',   sound: 'skyrim_quest'   },
  { label: 'Stop Right There!', icon: 'scum.png',           sound: 'scum'           },
  { label: 'It\'s a Trap!',     icon: 'ackbar.jpg',         sound: 'ackbar'         },
  { label: 'Alert',             icon: 'alert.jpg',          sound: 'alert'          },
  { label: 'Wii Shop',          icon: 'wii_shop.jpg',       sound: 'wii_shop'       },
  { label: 'Zelda Shop',        icon: 'zelda_shop.jpg',     sound: 'zelda_shop'     },
  { label: 'FF7 Victory',       icon: 'ff7.jpg',            sound: 'ff7'            },
  { label: 'Search for Traps',  icon: 'pookie.jpg',         sound: 'pookie'         },
  { label: 'Pokemon Battle',    icon: 'pokemon.jpg',        sound: 'pokemon'        },
  { label: 'Ghost Town',        icon: 'sean.png',           sound: 'sean'           },
  { label: 'Dun Dun Duuuunn!!', icon: 'dundundun.jpg',      sound: 'dundundun'      },
  { label: 'Bombom ba bom',     icon: 'trombone.jpg',       sound: 'fail_trombone'  },
  { label: 'A Lot of Damage',   icon: 'phil_swift.jpg',     sound: 'lotta_damage_1' },
  { label: 'A Lot of Damage?',  icon: 'jontron.png',        sound: 'lotta_damage_2' },
  { label: 'Bat Transition',    icon: 'bat_transition.jpg', sound: 'bat_transition' },
  { label: 'Yaaaaaayyyy',       icon: 'happy_children.jpg', sound: 'yaaay'          },
  { label: 'Bwa bwa bwaaa',     icon: 'sad_trombone.jpg',   sound: 'sad_trombone'   },
  { label: 'God Have Mercy',    icon: 'mercy.jpg',          sound: 'mercy'          },
  // new ToastButton(),
  { label: "The Garbage Man",   icon: 'garbage_man.png',   sound: 'garbage_man.mp3'       },
  { label: "The Tower!",        icon: 'the_tower.jpg',     sound: 'tower.mp3'             },
  { label: "Chest Opening",     icon: 'chest_opening.png', sound: 'chest_opening.mp3'     },
  { label: "Chest Prize",       icon: 'chest_prize.jpg',   sound: 'chest_prize.mp3'       },
  { label: "Gridders' Lament",  icon: 'dulcimer.jpg',      sound: 'dulcimer.mp3'          },
  { label: "Enemy Approaching", icon: 'enemy.jpg',         sound: 'enemy_approaching.mp3' },
  { label: "No God No",         icon: 'nogodno.jpg',       sound: 'nogodno.mp3'           },
  { label: "Wilhelm Scream",    icon: 'wilhelm.jpg',       sound: 'wilhelm.mp3'           },
  { label: "FF7 Fight",         icon: 'ff7fight.jpg',      sound: 'ff7fight.mp3'          },
  { label: "OOF",               icon: 'oof.jpg',           sound: 'oof.mp3'               },
  { label: "You Died!",         icon: 'mcoof.png',         sound: 'mcoof.mp3'             },
  { label: "Howie Scream",      icon: 'howie.jpg',         sound: 'howie.mp3'             },
  { label: "Curb",              icon: 'curb.jpg',          sound: 'curb.mp3'              },
  // new GuardQuoteButton(),
  // new ThatsHotButton(),
  // new DemocracyManifestButton(),
];
